apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"patternfly-app:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"patternfly-app\")].image"}]'
  labels:
    app: patternfly-app
    app.kubernetes.io/component: patternfly-app
    app.kubernetes.io/instance: patternfly-app    
  name: patternfly-app
spec:
  replicas: patched-in-overlays
  selector:
    matchLabels:
      app: patternfly-app
  template:
    metadata:
      labels:
        app: patternfly-app
    spec:
      containers:
        - name: patternfly-app
          image: image-registry.openshift-image-registry.svc:5000/patternfly-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
