---
apiVersion: build.openshift.io/v1 
kind: BuildConfig
metadata:
  labels:
    app: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
  namespace: nginx
spec:  
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: patternfly-app:latest
  runPolicy: Serial
  source:
    contextDir: .
    git:
      ref: main
      uri: https://github.com/richmitch/patternfly-app
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs-14:latest
      dockerfilePath: Dockerfile
      buildArgs:
        NODE_ENV: production
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 2Xg_nP5e1wJRw06cZxH9
    type: GitHub
  - generic:
      secret: NFSgTh54oY0xCAQn2PFc
    type: Generic
  - type: ConfigChange
  - type: ImageChange
      imageChange:
        automatic: true
        containerNames:
          - patternfly-app
        from:
          kind: ImageStreamTag
          name: nodejs-14:latest
