kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: patternfly-app

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: patternfly-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1